builds:
  - binary: ecsnv
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: ecsnv
    homepage: https://github.com/dineshgowda24/ecsnv
    tap:
      owner: dineshgowda24
      name: homebrew-dineshgowda
    commit_author:
      name: dineshgowda24
      email: dinesh240894@gmail.com

checksum:
  name_template: 'checksums.txt'
